name: MineScape
version: '0.2'
author: HoffmanTV
main: org.hoffmantv.minescape.MineScape
api-version: '1.20'
commands:
  help:
    description: Gives the player a list of available commands.
    usage: /help
  togglehologram:
    description: Allows player to turn on and off the skills menu
    usage: /togglehologram
  alwaysday:
    description: Toggle the always day feature.
    usage: /alwaysday <enable|disable>
    aliases: [ ad ]
    permission: minescape.alwaysday

permissions:
  minescape.help:
    description: Gives the player a list of available commands.
    default: op
  minescape.saveskills:
    description: Force saves all player skills.
    default: op
  minescape.skills:
    description: Opens the skills menu.
    default: not op
  minescape.alwaysday:
    description: Allows the user to toggle the always day feature.
    default: op
  minescape.createnpcAM:
    description: Allows the user to setup and NPC
    default: op
