name: MineScape
version: '0.1'
author: HoffmanTV
main: org.hoffmantv.minescape.MineScape
api-version: '1.20'
commands:
  help:
    description: Gives the player a list of available commands.
    usage: /help
  saveskills:
    description: Force saves all player skills.
    usage: /saveskills

permissions:
  minescape.help:
    description: Gives the player a list of available commands.
    default: op
  minescape.saveskills:
    description: Force saves all player skills.
    default: op
