name: MineScape
version: '0.2'
author: HoffmanTV
main: org.hoffmantv.minescape.MineScape
api-version: '1.20'
commands:
  help:
    description: Gives the player a list of available commands.
    usage: /help
  togglehologram:
    description: Allows player to turn on and off the skills menu
    usage: /togglehologram
  serverreload:
    description: Reloads the server without confirmation.
    usage: /serverreload
    permission: minescape.reload
    permission-message: ✘ You don't have permission to perform this action.
  trade:
    description: Initiates a trade with another player.
    usage: /trade <player>
    permission: minescape.trade
    permission-message: You don't have permission to use this command.
  accepttrade:
    description: Allows player to accept trade.
    usage: /accepttrade
  setspawn:
    description: Sets the global spawn point.
    usage: /setspawn
    permission: minescape.setspawn
    permission-message: You do not have permission to set the spawn point.
  spawn:
    description: Teleports you to the global spawn point.
    usage: /spawn
  reloadfishing:
    description: Reloads the fishing configuration.
    usage: /reloadfishing
    permission: minescape.reloadfishing
  addfishingspot:
    description: Adds a new fishing spot at your current location with specific fish and required level.
    usage: /addfishingspot <requiredLevel> <fishType1> <fishType2> ...
    permission: minescape.addfishingspot
permissions:
  minescape.help:
    description: Gives the player a list of available commands.
    default: op
  minescape.saveskills:
    description: Force saves all player skills.
    default: op
  minescape.skills:
    description: Opens the skills menu.
    default: not op
