name: MineScape
version: '0.1'
author: HoffmanTV
main: org.hoffmantv.minescape.MineScape
api-version: '1.20'
commands:
  help:
    description: Gives the player a list of available commands.
    usage: /help
  saveskills:
    description: Force saves all player skills.
    usage: /saveskills
  skills:
    description: Open the skills menu.
    usage: /skills
  alwaysday:
    description: Toggle the always day feature.
    usage: /alwaysday <enable|disable>
    aliases: [ ad ]
    permission: minescape.alwaysday

permissions:
  minescape.help:
    description: Gives the player a list of available commands.
    default: op
  minescape.saveskills:
    description: Force saves all player skills.
    default: op
  minescape.skills:
    description: Opens the skills menu.
    default: not op
  minescape.alwaysday:
    description: Allows the user to toggle the always day feature.
    default: op
